display_name: Liz Conlan
code_hosts:
  - host: github
    username: lizconlan
    sections:
      - type: contributor
        text: Projects I have collaborated on
      - type: own
        text: My projects
  - host: scraperwiki
    username: lizconlan
    sections:
      - type: own
        text: My Scraperwiki scrapers
      - type: contributor
        text: Scraperwiki scrapers I have edited