display_name: Liz Conlan
show_fork_banner: true
code_hosts:
  - host: github
    username: lizconlan
    sections:
      - type: own
        text: Code
      - type: contributor
        text: Collaborations