display_name: Liz Conlan
show_fork_banner: true
code_hosts:
  - host: github
    username: lizconlan
    sections:
      - type: contributor
        text: Collaborative Coding
      - type: own
        text: My Code
