display_name: Liz Conlan
show_fork_banner: true
code_hosts:
  - host: github
    username: lizconlan
    sections:
      - type: own
        text: Code
      - type: contributor
        text: Collaborations
      
  - host: scraperwiki
    username: lizconlan
    sections:
      - type: own   
        text: Scrapers
      - type: contributor
        text: Edited Scrapers